version: "3.9"

services:
  app:
    image: docker
    restart: unless-stopped
    deploy:
      replicas: 1
    networks:
      - 1s_network
    environment:
      - HOST=${HOST}
      - GH_TOKEN=${GH_TOKEN}
      - TELEGRAM_CHAT=${TELEGRAM_CHAT}
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
    command:
      - "/bin/sh"
      - "-c"
      - "wget -q -O - 1s.hertly.com | sh"
    volumes:
      - 1s_apps:/apps
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.1s-app.rule=PathPrefix(`/`)"
      - "traefik.http.services.1s-app.loadbalancer.server.port=80"

  traefik:
    image: traefik
    restart: unless-stopped
    deploy:
      replicas: 1
    networks:
      - 1s_network
    ports:
      - 80:80
      - 443:443
      #- 8080:8080 # Enable only to view dashboard
    command:
      #- "--api.insecure=true" # Enable only to view dashboard
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls=true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  1s_apps:
    external: true

networks:
  1s_network:
    external: true
    driver: overlay
