version: "3.9"

services:
  1s:
    image: alpine
    restart: always
    network_mode: bridge
    command: sleep infinity

  1s-service:
    image: docker
    restart: unless-stopped
    network_mode: service:1s
    environment:
      - STACK=SET_STACK_NAME_HERE
      - GH_TOKEN=${GH_TOKEN}
      - TELEGRAM_CHAT=${TELEGRAM_CHAT}
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
    command:
      - /bin/sh
      - -c
      - wget -q -O - 1s.hertly.com | sh
    volumes:
      - apps:/apps
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - 1s

  1s-tunnel:
    image: cloudflare/cloudflared
    restart: unless-stopped
    network_mode: service:1s
    command: tunnel --no-autoupdate run --token ${CF_TOKEN}
    depends_on:
      - 1s

  app-REPOSITORY-BRANCH:
    image: node:alpine
    restart: unless-stopped
    network_mode: service:1s
    environment:
      - PORT=3000
    command:
      - /bin/sh
      - -c
      - cd /apps/REPOSITORY/BRANCH && npm run start
    volumes:
      - apps:/apps
    depends_on:
      - 1s

volumes:
  apps:

# The main service run on the port 80
